/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilepageUuidRouteImport } from './routes/profilepage.$uuid'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilepageUuidRoute = ProfilepageUuidRouteImport.update({
  id: '/profilepage/$uuid',
  path: '/profilepage/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/landing': typeof LandingRoute
  '/profile': typeof ProfileRoute
  '/profilepage/$uuid': typeof ProfilepageUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/landing': typeof LandingRoute
  '/profile': typeof ProfileRoute
  '/profilepage/$uuid': typeof ProfilepageUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitations': typeof InvitationsRoute
  '/landing': typeof LandingRoute
  '/profile': typeof ProfileRoute
  '/profilepage/$uuid': typeof ProfilepageUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitations'
    | '/landing'
    | '/profile'
    | '/profilepage/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invitations' | '/landing' | '/profile' | '/profilepage/$uuid'
  id:
    | '__root__'
    | '/'
    | '/invitations'
    | '/landing'
    | '/profile'
    | '/profilepage/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitationsRoute: typeof InvitationsRoute
  LandingRoute: typeof LandingRoute
  ProfileRoute: typeof ProfileRoute
  ProfilepageUuidRoute: typeof ProfilepageUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilepage/$uuid': {
      id: '/profilepage/$uuid'
      path: '/profilepage/$uuid'
      fullPath: '/profilepage/$uuid'
      preLoaderRoute: typeof ProfilepageUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitationsRoute: InvitationsRoute,
  LandingRoute: LandingRoute,
  ProfileRoute: ProfileRoute,
  ProfilepageUuidRoute: ProfilepageUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
